using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class ManagingScenes : MonoBehaviour
{
    public int sceneNumber;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKey(KeyCode.Escape))
        {
            Application.Quit();
        }

        if (sceneNumber == 0)
        {
            if (Input.GetKeyDown(KeyCode.Space))
            {
                Debug.Log("Start game");
                SceneManager.LoadScene("Level1");
            }
        }
    }
}
