using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using TMPro;

public class UIController : MonoBehaviour
{
    //The UI Controller is a Singleton
    //An instance is a saved copy of this game object so that it can be accessed from anywhere
    public static UIController Instance { get; private set; }

    [Tooltip("The destructible of the player so we can tell if the game is over")]
    public Destructible playerDestructible;
    [Tooltip("A list of all the heart containers for the player")]
    public List<GameObject> heartContainers;
    [Tooltip("The text object to modify showing coin count")]
    public TMP_Text coinCountText;

    //A var to know whether or not we have lost the game
    private bool hasLost = false;
    //The current coin coint in the game
    private int coinCount;

    //Awake happens once at the beginning of the game, even before Start()
    public void Awake()
    {
        //If we have an instance of a UI Controller already 
        if (Instance != null && Instance != this)
        {
            //Destroy ourselves so we never have more than 1 UiController
            //This is the primary attribute of a Singleton
            Destroy(this);
        }
        else
        {
            //If we don't, set the instance to this UiController
            Instance = this;
        }
    }

    // Start is called before the first frame update
    void Start()
    {
        //If the player is dead
        if (playerDestructible == null)
        {
            //Set has lost to true
            hasLost = true;

            //Let the game developer know we probably should have a player
            Debug.LogWarning("UI Controller has no Player object on Start");
        }

        //Set our coin count to 0
        coinCount = 0;
        //Call the modify coin count function to force a text update
        ModifyCoinCount(0);
    }

    // Update is called once per frame
    void Update()
    {
        //ask for the current hitpoints
        if (playerDestructible != null)
        {
            int healthPoints = playerDestructible.GetHitPoints();

            //For every heart in our heart list
            for (int i = 0; i < heartContainers.Count; i++)
            {
                //If we have enough hitpoints...
                if (i < healthPoints)
                {
                    //Turn it on
                    heartContainers[i].SetActive(true);
                }
                else
                {
                    //If not, turn it off
                    heartContainers[i].SetActive(false);
                }
            }
        }
    }

    //Change the number of coins we have
    public void ModifyCoinCount(int numCoins)
    {
        //Add to the variable
        coinCount += numCoins;

        //If we have coin text...
        if (coinCountText != null)
        {
            //Change the text to our new count
            coinCountText.text = "X " + coinCount;
        }
    }

    //public void LoadLevel(string sceneName)
    //{
    //    SceneManager.LoadScene(sceneName);
    //}
    
    //public void RestartLevel()
    //{
    //    SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    //}

}